language: node_js
node_js:
  - "7"
script:
  - echo "Deploy!!"
install:
  - npm install -g firebase-tools
after_success:
  - firebase deploy --project watermelon-market --token 03zp4mlmW094zCgYIARAAGAMSNwF-L9IrTVQNrCl2Fvq_dCNoPT_DonwMO5M8WRbYJJbIe9_SLhFt3Fyq4gQI_391pigjp7LePYA
